### PR TITLE
Tasks/c 6964 chinese locale fallback

### PR DESCRIPTION
**Pull request by bsiegel**
Completes https://youtrack.mobiledefense.com/issue/c-6964

Rebased on top of (and depends on) #1.

### CODE REVIEW

**Comment by bsiegel** [comment]
Code coverage at a6e92b8: [coverage.zip](https://github.com/mobiledefense/http_accept_language/files/105762/coverage.zip)

**Comment by jbcden** [comment]
Could you add some documentation about around the interface for adding a custom matcher and what a matcher is expected to implement?

**Comment by jbcden** [comment]
:+1: Ready for merge.

**Note:** Please interactively rebase this branch onto latest master and squash any fixups before merging this pull request.

~~~shell
$ git checkout master
$ git pull origin master

$ git checkout <this-branch-name>
$ git rebase -i master --autosquash
~~~

**Comment by bsiegel** [comment]
> Could you add some documentation about around the interface for adding a custom matcher and what a matcher is expected to implement?

I will open a separate PR for general matcher-related documentation

**Pull request merged**
